return {
    -- "stevearc/conform.nvim",
    -- event = { "BufReadPre", "BufNewFile" },
    -- config = function()
    --     local conform = require("conform")
    --
    --     conform.setup({
    --         formatters_by_ft = {
    --             javascript = { { "prettierd", "prettier" } },
    --             typescript = { { "prettierd", "prettier" } },
    --             css = { { "prettierd", "prettier" } },
    --             html = { { "prettierd", "prettier" } },
    --             json = { { "prettierd", "prettier" } },
    --             yaml = { { "prettierd", "prettier" } },
    --             markdown = { { "prettierd", "prettier" } },
    --             -- gotmpl = { { "prettierd", "prettier" } },
    --         },
    --         format_on_save = nil,
    --     })
    --
    --     vim.keymap.set({ "n", "v" }, "<leader>ff", function()
    --         conform.format({
    --             lsp_fallback = true,
    --             async = false,
    --             timeout_ms = 1000,
    --         })
    --     end, { desc = "[F]ormat [F]ile" })
    -- end,
}
